# Generated by Django 5.2.12 on 2026-04-17 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_storesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storesettings",
            options={},
        ),
    ]
