# Generated by Django 5.2.12 on 2026-04-19 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0004_add_type_to_presetsize"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PAID", "Pagado"),
                            ("REFUNDED", "Reembolsado"),
                            ("PARTIALLY_REFUNDED", "Parcialmente reembolsado"),
                            ("FAILED", "Fallido"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("UNFULFILLED", "Sin cumplir"),
                            ("PREPARING", "Preparando"),
                            ("READY_FOR_PICKUP", "Listo para recoger"),
                            ("SHIPPED", "Enviado"),
                            ("DELIVERED", "Entregado"),
                            ("RETURNED", "Devuelto"),
                        ],
                        db_index=True,
                        default="UNFULFILLED",
                        max_length=20,
                    ),
                ),
                ("is_cancelled", models.BooleanField(db_index=True, default=False)),
                ("items_total_minor", models.IntegerField()),
                ("shipping_cost_minor", models.IntegerField(default=0)),
                ("tax_minor", models.IntegerField(default=0)),
                ("total_minor", models.IntegerField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=100)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("return_tracking_id", models.CharField(blank=True, max_length=100)),
                ("guest_access_code", models.CharField(blank=True, max_length=6)),
                (
                    "guest_access_code_expiry",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("street", models.CharField(max_length=255)),
                ("address_extra", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(max_length=20)),
                ("province", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="ES", max_length=2)),
                (
                    "shipping_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Domicilio"),
                            ("STORE", "Tienda"),
                            ("PICKUP", "Punto de recogida"),
                        ],
                        default="HOME",
                        max_length=10,
                    ),
                ),
                ("store_location_id", models.CharField(blank=True, max_length=100)),
                ("pickup_location_id", models.CharField(blank=True, max_length=100)),
                ("pickup_search", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Cambio de estado"),
                            ("INCIDENT", "Incidencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("snapshot_status", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("actor", models.CharField(max_length=50)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_snapshot", models.CharField(max_length=255)),
                ("price_minor_snapshot", models.IntegerField()),
                ("size_snapshot", models.CharField(blank=True, max_length=50)),
                ("color_snapshot", models.CharField(blank=True, max_length=50)),
                ("quantity", models.IntegerField()),
                ("subtotal_minor", models.IntegerField()),
                ("quantity_returned", models.IntegerField(default=0)),
                ("quantity_return_requested", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["email", "-created_at"], name="orders_orde_email_493ddc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status", "fulfillment_status"],
                name="orders_orde_payment_85449e_idx",
            ),
        ),
    ]
