# Generated by Django 5.2.12 on 2026-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_slug_partial_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresetSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["sort_order", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["color_order", "sku"]},
        ),
        migrations.AddField(
            model_name="category",
            name="featured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="mobile_image",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productimage",
            name="color_label",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="productimage",
            name="source_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="color_hex",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="color_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.CreateModel(
            name="PresetColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("hex", models.CharField(max_length=16)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "hex"),
                        name="products_presetcolor_name_hex_uniq",
                    )
                ],
            },
        ),
    ]
