# Generated by Django 5.2.12 on 2026-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_phase3_store_and_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="presetsize",
            name="type",
            field=models.CharField(
                choices=[("clothing", "Clothing"), ("shoe", "Shoe")],
                default="clothing",
                max_length=16,
            ),
        ),
    ]
